### PR TITLE
Refactor and update the admin subscription bulk action handling to support HPOS environments

### LINKED ISSUE #301: [HPOS] List Subscriptions admin screen: Uncaught exception during bulk update subscription status
## Describe the bug

When doing a bulk update of subscription status from the subscriptions list admin screen an uncaught exception is thrown.

```
Fatal error: Uncaught Exception: Unable to change subscription status to "processing". 
in woocommerce-subscriptions-core/includes/class-wc-subscription.php:433 

Stack trace: 
#0 woocommerce/src/Internal/Admin/Orders/ListTable.php(1145): WC_Subscription->update_status('processing', 'Order status ch...', true) 
#1 woocommerce/src/Internal/Admin/Orders/ListTable.php(1068): Automattic\WooCommerce\Internal\Admin\Orders\ListTable->do_bulk_action_mark_orders(Array, 'processing') 
#2 woocommerce/src/Internal/Admin/Orders/PageController.php(238): Automattic\WooCommerce\Internal\Admin\Orders\ListTable->handle_bulk_actions() 
#3 woocommerce/src/Internal/Admin/Orders/PageController.php(122): Automattic\WooCommerce\Internal\Admin\Orders\PageController->setup_action_list_orders() 
#4 [internal function]: Automattic\WooCommerce in woocommerce-subscriptions-core/includes/class-wc-subscription.php on line 433
```

image

## To Reproduce

1. With HPOS enabled and set as the default order storage, click on the subscriptions menu item in wp-admin.
2. Select one or more subscriptions and update the status.
3. See error
image

### LINKED ISSUE #320: [HPOS] Bulk actions redirect to orders page
## Describe the bug

With HPOS enabled and using [HPOS Admin UI support](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) and associated [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/35658) bulk actions don't function.

Blocked by https://github.com/woocommerce/woocommerce/issues/35750
Related to #321 

image

## To Reproduce

1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. Click on one or more subscriptions and perform a bulk action e.g. ('Move to Trash')
3. Notice that the action did not happen

### Expected behavior

Bulk actions work as expected.

### Actual behavior

The user is redirected to the Orders page.

### LINKED ISSUE #364: [HPOS] Using subscription actions on admin subscriptions list table results in "The link you followed has expired" errors
## Describe the bug

When using the Subscription actions on the admin subscriptions list table, you get the following error:

Screen Shot 2023-01-10 at 3 26 59 pm

```
The link you followed has expired
```

## To Reproduce

1. Enable HPOS
2. Purchase a subscription
3. Go to **WooCommerce > Subscriptions** on your admin dashboard.
4. Hover a subscription and click "Suspend"
5. Note the error. 

Repeat for other actions like activating, cancelling etc. 

### Expected behavior

The link shouldn't be expired.

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #364
Fixes #320
Fixes #301

## Description

On HPOS environments, admin bulk actions and subscription action links were erroring or redirecting to the orders table. There were a few different issues that this PR addresses. 

1. On HPOS WC expects third parties to hook onto the dynamic hook `handle_bulk_actions-{woocommerce_page_wc-orders--shop_subscription}` to tell it which page to redirect to after processing bulk actions. This PR does that.
    - #320 
3. For the individual subscription actions, WC changed the nonce flag (from the default WP one `bulk-posts` to `bulk-orders`). This change in nonce resulted in the `The link you followed has expired` errors.
     - #364

This PR fixes both those issues and includes some general tidying of the relevant code. 

## How to test this PR

1. Enable HPOS. 
2. Purchase at least 1 subscription.
3. Go to WooCommerce > Subscriptions on admin
4. Select at least 1 subscription, and choose a bulk action from the dropdown. 
5. Click apply.
6. The selected subscriptions should be updated. 
7. A notice should appear explaining the number of subscriptions updated. 
8. Hover over individual subscription and click one of the action links (suspend, activate, cancel etc)
9. The relevant subscription should be updated. 
7. A notice should appear explaining the number of subscriptions updated. 
10. Repeat for CPT.

Screen Shot 2023-01-11 at 10 14 11 am

Screen Shot 2023-01-11 at 10 19 32 am

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Review by mattallan — COMMENTED** [review]
From my testing, I checked the following flows (see below) and I found that using the bulk actions to trash, untrash & delete subscriptions isn't working on this branch when HPOS is disabled.

I checked out `trunk` and it's working.

---

#### With HPOS enabled:
- [x] Using subscription actions on list table items
  - [x] Activate an on-hold subscription
  - [x] Suspend active subscription
  - [x] Cancel an active subscription (goes pending cancelled)
  - [x] Trash subscription
  - [x] Delete permenantly
- [x] Using bulk actions
  - [x] Performed a bulk action that was invalid (i.e. update a canceled subscription to on-hold). Confirmed error notice
  - [x] Activate multiple subscriptions using bulk actions (one pending cancelled, one on-hold)
  - [x] Cancel a subscription
  - [x] Suspend a subscription
  - [x] Trash a subscription
  - [x] Untrash all trashed subscriptions
  - [x] Delete permanently
  - [ ] Cancel and remove personal data :x:
     - I've opened a separate issue for this https://github.com/Automattic/woocommerce-subscriptions-core/issues/376

#### With HPOS off:
- [x] Using subscription actions on list table items
  - [x] Activate an on-hold subscription
  - [x] Suspend active subscription
  - [x] Cancel an active subscription (goes pending cancelled)
  - [x] Trash subscription
  - [x] Delete permenantly
- [x] Using bulk actions
  - [x] Performed a bulk action that was invalid (i.e. update a canceled subscription to on-hold). Confirmed error notice
  - [x] Activate multiple subscriptions using bulk actions (one pending cancelled, one on-hold)
  - [x] Cancel a subscription
  - [x] Suspend a subscription
  - [x] Trash a subscription
  - [x] Untrash all trashed subscriptions
  - [x] Delete permanently
  - [x] Cancel and remove personal data

**Comment by james-allan** [comment]
>  Trash a subscription ❌
> Untrash all trashed subscriptions ❌
> Delete permanently :x:
> Cancel and remove personal data ❌

I've fixed this with [c97db78](https://github.com/Automattic/woocommerce-subscriptions-core/pull/367/commits/c97db78584938e3f39181f96192a952db5b417f1). 

Turns out I wasn't returning out of `parse_bulk_actions()` when processing actions that are handled by WC or WP core.

**Comment by mattallan** [comment]
I've tested the latest changes and confirmed it's fixed the issues I found. There's still one issue remaining with fixing "Cancel and remove personal data" bulk action on stores with HPOS but I've created a separate issue for this as it'll require some bigger changes

**Review by mattallan — APPROVED** [review]
This PR needs a changelog now but apart from that this is good to merge

**Pull request merged**
