### PR TITLE
Fix subscription table is empty in mobile view when HPOS is enabled.

### LINKED ISSUE #584: Subscription table is empty in mobile view.
## Describe the bug
With HPOS enabled, the subscription table is empty in mobile view. 
Issue reported in p1711127516765309-slack-C7U3Y3VMY.

## To Reproduce

- Create a test site.
- Install WooCommerce `8.7.0` and Woo Subscriptions `6.0.0`.
- Enable HPOS.
- Create at least one subscription.
- Go to the Subscriptions page at `/wp-admin/admin.php?page=wc-orders--shop_subscription`.
- Notice that the subscription is present in the table.
- Now inspect at a mobile breakpoint (max-width: 782 px). Notice that the table is empty.

### Expected behavior
- The list of subscriptions should load in the mobile view as well.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #584 

This PR fixes to issues related to HPOS-
- With HPOS enabled, the subscription table is empty in mobile view.
- With HPOS enabled, the WooCommerce page header is missing from the Subscriptions page.

## How to test this PR

1. Enable HPOS from **WooCommerce > Settings > Advanced > Features** page.
2. Create at least one subscription.
3. Go to **WooCommerce > Subscriptions**.
4. Notice that the subscription is present in the table.
5. In `trunk` branch, inspect at a mobile breakpoint (max-width: 782 px). Notice that the table is empty.
6. Also, the WooCommerce page header is missing on the Subscriptions page.

7. In this branch, inspect at a mobile breakpoint (max-width: 782 px). Notice that the subscriptions are rendered correctly in the table. 
8. In this branch, the WooCommerce page header is present on the Subscriptions page for both desktop and mobile views.

### CODE REVIEW

**Review by james-allan — APPROVED** [review]
Changes look good to me. 

I confirmed the WooCommerce header was missing on `trunk` and visible on this PR.

I also confirmed that setting the primary column fixed the issue on mobile view. 

Nice work here @Mayisha! I wouldn't have guessed that the lack of a primary column is what was behind this. 


| `trunk` | This branch |
|--------|--------|
| Screenshot 2024-04-29 at 3 24 00 PM | 326335380-a221d18b-174c-4ec3-9e22-ad3b108b54d5 |
| Screenshot 2024-04-29 at 3 23 44 PM | Screenshot 2024-04-29 at 3 22 53 PM |

**Comment by Mayisha** [comment]
@james-allan with the new Gutenberg [release](https://wordpress.org/plugins/gutenberg/), the minimum supported version of PHP is `7.2`. Two of the tests are failing because of this. Shall we remove the tests with PHP `7.1` and older versions? Do we still need to support these older versions of PHP? :eyes:

**Comment by mattallan** [comment]
> Shall we remove the tests with PHP 7.1 and older versions? Do we still need to support these older versions of PHP? 👀

Good call! The oldest WooCommerce we support (7.7) requires PHP 7.3 so I don't think we need to support these older versions anymore.

I've updated the GH workflows in a separate PR (https://github.com/Automattic/woocommerce-subscriptions-core/pull/612). I'll merge this once I confirm the tests are running smoothly :)

**Comment by mattallan** [comment]
Thanks @Mayisha for these changes! CH checks are passing, so I'm going to merge this now 🙌

**Comment by Mayisha** [comment]
Thanks @mattallan :tada:

**Pull request merged**
