### PR TITLE
Fix subscription product sync options for yearly products not being editable

### PR DESCRIPTION
**Pull request by james-allan**
Fixes https://github.com/woocommerce/woocommerce-subscriptions/issues/4588

## Description

In https://github.com/Automattic/woocommerce-subscriptions-core/pull/508, the number input elements that enable store admin to select the day of the month for which yearly subscription products are synced to was changed from a `<input type="number" ... >` to a select2 (by giving it the `wc-enhanced-select` class. This essentially broke these elements because attempting to turn input elements into a select2 powered element didn't work - ie they had no options.

<p align="center">
Screenshot 2024-03-09 at 10 43 12 am
</p>

This PR fixes this by turning these elements into true select2 elements via `<select>` and `<option>` elements.

<p align="center">

Screenshot 2024-03-09 at 3 35 06 pm
</p>

#### Simple Subscription.

1. Go to **Products → Add new**
2. Choose **Simple subscription** from the product type dropdown.
3. Enter a price and choose "yearly" as the subscription period.
4. In the "Synchronise renewals" section choose a month
5. Try to set a day. 
6. On `trunk` you'll notice the dropdown is empty. 
7. On this branch it should have all the days of the chosen month. eg
  - 28 for February
  - 30 for September
  - 31 for January

| Before | After |
|--------|--------|
| Screenshot 2024-03-14 at 3 48 28 pm | Screenshot 2024-03-14 at 3 54 13 pm | 

8. Confirm that saving the synchronisation product is correctly sets the product as a synced product to that date. 
9. Confirm that unselecting a month option unsets the synchronisation property from the product. 
10. Confirm that weekly, monthly products are unaffected by this change.

#### Variable Subscription

1. Go to **Products → Add new**
2. Choose **Variable subscription** from the product type dropdown.
3. Create variations 
4. Enter a price and choose "yearly" as the subscription period.
5. In the "Synchronise renewals" section choose a month (eg January)
6. Try to set a day. 
7. On `trunk` you'll notice the date selector is a number input. 
8. On this branch it should be select2 with all the days of the chosen month as options. eg
  - 28 for February
  - 30 for September
  - 31 for January

| Before | After |
|--------|--------|
| Screenshot 2024-03-14 at 4 14 05 pm | Screenshot 2024-03-14 at 4 15 13 pm| 

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Review by mattallan — APPROVED** [review]
`trunk`
- :x: Simple subscriptions
- :+1: Variation subscriptions

`fix/4588-fix-yearly-sync-product-settings`
- :+1: Simple subscriptions (weekly, monthly, yearly sync)
- :+1: Variation subscriptions (weekly, monthly, yearly)
- :+1: Confirmed updating/saving sync not impacted

---

Maybe we push this to another issue/PR or not bother since we're going to focus on the new Product editor, but the length of these fields is all over the place 😅

Some of these are new to this PR like the variation yearly sync field being slightly off but it looks like most of these issues have been around for a while, so I don't think it should be block the PR. Thoughts?


**Simple subscriptions**

Monthly/weekly Sync:
image

Yearly sync:
image

**Variable subscriptions**

Monthly/weekly sync:
image

Yearly sync (very minor):
image

**Comment by james-allan** [comment]
I didn't realise the fields I changed in this PR were that off. I guess everything else being out of line made that harder to see. 

I've pushed a few commits that fix those alignment issues.

### Simple Subscription

<p align="center">
Screenshot 2024-03-18 at 4 26 25 pm
</br>
<sup>Weekly products only have 1 sync element</sup>

Screenshot 2024-03-18 at 4 27 05 pm
<sup>Yearly products only have 2 sync elements</sup>
</p>

### Variable Subscription

<p align="center">
Screenshot 2024-03-18 at 2 29 58 pm
</p>

**Review by mattallan — APPROVED** [review]
Thanks @james-allan !!

I'm going to approve this PR and leave it up to you whether you want to fix this 😂 But I noticed variable subscription products still has a very minor issue:

https://github.com/Automattic/woocommerce-subscriptions-core/assets/2275145/f534397e-e502-4656-b5a9-1243d639616e

When you change the period from year to month, the length of the sync field changes.

Not sure if the single sync field is supposed to be the full-length like it is for simple products?

**Comment by james-allan** [comment]
Hey Matt. I think I've fixed all those issues now. 😅 

### Simple product

| Yearly (2 sync fields) | Weekly (1 sync field) |
|--------|--------|
| Screenshot 2024-03-21 at 5 47 00 pm | Screenshot 2024-03-21 at 5 46 52 pm |

### Variable product

| Yearly (2 sync fields) | Weekly (1 sync field) |
|--------|--------|
| Screenshot 2024-03-21 at 5 49 01 pm| Screenshot 2024-03-21 at 5 49 21 pm|

**Review by mattallan — APPROVED** [review]
Thanks @james-allan for persisting with this one and fixing all of the CSS issues!

I've tested the latest changes and couldn't find any issues:

#### Simple Subscription :+1:
| Weekly/Monthly | Yearly |
|--------|--------|
| image | image | 

#### Variable Subscription :+1:
| Weekly/Monthly | Yearly |
|--------|--------|
| image | image |

**Pull request merged**
