### PR TITLE
Remove the REST API and webhook files and from the autoloader

### LINKED ISSUE #3: Port subscription REST API endpoints feature over to the extension
The REST API subscription endpoints currently allow users to change a subscription that is incompatible with WC Pay Subscriptions. With that in mind, we need to remove the REST API files out of core and introduce them directly to the plugin. 

The REST API wasn't included on the original feature matrix here: paJDYF-27L-p2

### PR DESCRIPTION
**Pull request by james-allan**
### Description

Removes the REST API feature from `subscriptions-core`.

### To test: 

1. Git clone `woocommerce-subscriptions-core` into wp-plugins and checkout this branch (this will make WC Subscriptions 4.0+ and WC Payments load `subscriptions-core` from this repo)
1. **Deactivate** the Subscriptions extension
2. [Create REST API credentials](https://docs.woocommerce.com/document/woocommerce-rest-api/#section-2) for your site.
2. Using a tool like Postman send a subscription-related request.
   - eg **` GET`** `http://example.local/wp-json/wc/v3/subscriptions/{ID}`.
3. On `trunk`, the request will go through and you should receive a valid response. 
4. On this branch you will get the following error response. 

```json
{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method.",
    "data": {
        "status": 404
    }
}
```

**Webhooks**

1. Git clone `woocommerce-subscriptions-core` into wp-plugins and checkout this branch (this will make WC Subscriptions 4.0+ and WC Payments load `subscriptions-core` from this repo)
1. **Deactivate** the Subscriptions extension
1. Go to **WooCommerce > Settings > Advanced > Webhooks**.
1. With WC Subscriptions active or on `trunk`,  you can still create subscription webhooks. https://d.pr/i/7vJIfz
1. On this branch there will be no subscription-related webhook topics. https://d.pr/i/JjjzCR

closes #3

### CODE REVIEW

**Review by shendy-a8c — COMMENTED** [review]
Tested well per testing instructions.

I have couple questions though:
1. Wanting to make sure there is no references to the deleted classes, I find this [`WC_REST_Subscriptions_v1_Controller` reference](https://github.com/Automattic/woocommerce-subscriptions-core/blob/remove/rest_api/includes/class-wcs-webhooks.php#L141) of the class from the deleted `includes/api/v1/class-wc-rest-subscriptions-v1-controller.php`. Is that OK? It might break webhook setup or something as it's called [here](https://github.com/Automattic/woocommerce-subscriptions-core/blob/remove/rest_api/includes/class-wcs-webhooks.php#L31).

2. Searching `WC_API_Subscriptions` (class from deleted `includes/api/legacy/class-wc-api-subscriptions.php`), I also find it's usage [here](https://github.com/Automattic/woocommerce-subscriptions-core/blob/remove/rest_api/includes/class-wcs-webhooks.php#L134-L135). Is that OK?

**Comment by james-allan** [comment]
Great questions @shendy-a8c! 

Something I forgot about removing the REST API files is that it has a ripple on effect on the Webhooks given we generate the payload using the same REST API response. 

This means, if we want to remove the REST API, we will also need to remove the webhooks feature.

**Comment by james-allan** [comment]
> we will also need to remove the webhooks feature.

I've updated this PR and the accompanying PR to move the webhooks and auth classes from Core into the plugin. I've also updated the two PR descriptions to reflect this change.

**Review by shendy-a8c — APPROVED** [review]
LGTM!

 I wonder once this PR is merged, how can this change be picked up by wcpay. Do we have to keep increasing version each time there is a change in subscription-core?

**Comment by mattallan** [comment]
> Do we have to keep increasing version each time there is a change in subscription-core?

Yeah this is my understanding.

I'm going to look into this this week, but off the top of my head, we'll have to tag a new version of subscriptions core and then in WCPay, update the `woocommerce/subscriptions-core` version in wcpay's composer.json file.

Do you have any suggestions?

**Pull request merged**
