### PR TITLE
Update JS linting CI

### LINKED ISSUE #58: Update JS to match woocommerce/eslint-plugin rules
## Describe the bug

Currently javascript isn't meeting all of the standards set in [@woocommerce/eslint-plugin](https://www.npmjs.com/package/@woocommerce/eslint-plugin)

## To Reproduce

1. Run `wp-scripts lint-js assets/src/js`
2. see errors 

### Expected behavior

No errors / warnings

### Actual behavior

```
  6:1   error  Missing JSDoc @param "props.components" declaration                                                                   jsdoc/require-param
  13:0   error  Missing @param "props.components"                                                                                     jsdoc/check-param-names
  20:0   error  @param "props.useSelectShippingRate" does not exist on props                                                          jsdoc/check-param-names
  22:48  error  Insert `·`                                                                                                            prettier/prettier
  30:2   error  Insert `·`                                                                                                            prettier/prettier
  37:18  error  Replace `subscriptions` with `·subscriptions·`                                                                        prettier/prettier
  38:10  error  Replace `(recurringCart)·=>·recurringCart.shipping_rates` with `·(·recurringCart·)·=>·recurringCart.shipping_rates·`  prettier/prettier
  39:13  error  Replace `Boolean` with `·Boolean·`                                                                                    prettier/prettier
  41:4   error  Replace `subscriptions` with `·subscriptions·`                                                                        prettier/prettier
  43:33  error  Insert `·`                                                                                                            prettier/prettier
  46:3   error  Insert `·`                                                                                                            prettier/prettier
  47:34  error  Insert `·`                                                                                                            prettier/prettier
  50:3   error  Insert `·`                                                                                                            prettier/prettier
  51:22  error  Replace `({·package_id:·packageId,·...packageData·}` with `·(·{·package_id:·packageId,·...packageData·}·`             prettier/prettier
  53:9   error  Replace `packageId` with `·packageId·`                                                                                prettier/prettier
  54:15  error  Replace `packageId` with `·packageId·`                                                                                prettier/prettier
  55:17  error  Replace `packageData` with `·packageData·`                                                                            prettier/prettier
  56:17  error  Replace `collapsible` with `·collapsible·`                                                                            prettier/prettier
  57:14  error  Replace `shouldCollapse` with `·shouldCollapse·`                                                                      prettier/prettier
  58:15  error  Replace `shouldShowItems` with `·shouldShowItems·`                                                                    prettier/prettier
  59:22  error  Replace `noResultsMessage` with `·noResultsMessage·`                                                                  prettier/prettier
  60:18  error  Replace `renderOption` with `·renderOption·`                                                                          prettier/prettier
  62:3   error  Insert `·`                                                                                                            prettier/prettier

✖ 23 problems (23 errors, 0 warnings)
  21 errors and 0 warnings potentially fixable with the `--fix` option.
```
## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? no
- [x] Does this issue affect WooCommerce Payments? no

## Additional context

see also #32

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #58

## Description

Adds JS linting

## How to test this PR

1. `npm run lint:js` 
2. should have no errors or warnings

## Product impact

- [x] Will this PR affect WooCommerce Subscriptions? no
- [x] Will this PR affect WooCommerce Payments? no

### CODE REVIEW

**Comment by brucealdridge** [comment]
@aprea I found after committing that there is a command `format:js` in package.json. Currently CI and pre-commit hooks only run `lint:js` (and this only runs on `assets/js/src`)

However broadening the scope seems to fix more than just "errors" but also uses prettier to format. 
Do we bite the bullet and format all js in the repo?

And we're hitting css rules now :/

**Comment by mattallan** [comment]
Not to intrude on this PR but with the CSS linting issues, what are your thoughts on using the same rules as [WC Payments](https://github.com/Automattic/woocommerce-payments/blob/develop/.stylelintrc.json)?

It looks like most of the issues were 80 characters long and `selector-class-pattern` related which are both set to `null` in WC Payments so I'm thinking it's fine for us to do something similar?

**Comment by brucealdridge** [comment]
> It looks like most of the issues were 80 characters long and `selector-class-pattern` related which are both set to `null` in WC Payments so I'm thinking it's fine for us to do something similar?

Sounds like a good plan!

**Comment by aprea** [comment]
@brucealdridge apologies for the slow review on this PR. I'm noticing a few changes when I run `npm run format:js`.

Keen to hear your thoughts on whether we should add these changes to this PR to establish a good baseline?

p.s. I think we'll need to add a `.eslintignore` file as I noticed changes were introduced in vendor files (e.g. `assets/js/admin/moment.js`) when I run `npm run format:js`.

**Comment by brucealdridge** [comment]
> Keen to hear your thoughts on whether we should add these changes to this PR to establish a good baseline?

I was keen to hear your thoughts! 
I'd opt to lean into reformatting the entire repo (excluding those vendor files.) It's a pain but it is a one off rather than the ongoing hassle of having files that don't meet the standard. 
If we go the alternate route, it leads to either manually ignoring rules or adding file exclusions. 

> p.s. I think we'll need to add a `.eslintignore` file as I noticed changes were introduced in vendor files (e.g. `assets/js/admin/moment.js`) when I run `npm run format:js`.

I added these to the prettier ignore file which I thought was the source of this. Clearly I missed this.

**Comment by aprea** [comment]
>I was keen to hear your thoughts!
I'd opt to lean into reformatting the entire repo (excluding those vendor files.) It's a pain but it is a one off rather than the ongoing hassle of having files that don't meet the standard.

Same! Let's go ahead with this if you're okay with it

**Comment by brucealdridge** [comment]
> > I was keen to hear your thoughts!
> > I'd opt to lean into reformatting the entire repo (excluding those vendor files.) It's a pain but it is a one off rather than the ongoing hassle of having files that don't meet the standard.
> 
> Same! Let's go ahead with this if you're okay with it

I've split the automated / manual fixes into separate commits to make review easier. The only outstanding issue that I couldn't resolve was `@wordpress/i18n-translator-comments` vs max line length. It doesn't appear multiline translator comments are allowed so have disabled the rule as a workaround (which has also been done on WC Payments)

**Comment by brucealdridge** [comment]
@aprea I worked through the errors in `assets/js` and quickly saw that there were no easy fixes. So merged [your PR](https://github.com/Automattic/woocommerce-subscriptions-core/pull/59/commits/dc1754dd28cd9540ac723af5b6b3d66ea9e3b544) in and made a minor change to package.json to remove the paths specified so it can be run on commit with just the changed files. I also swapped the order of the commands so formatting is done before linting.

**Review by aprea — APPROVED** [review]
This LGTM and is working as expected :shipit:

**Pull request merged**
