### PR TITLE
Fix PHPCS violations in `WC_Subscriptions_Tracker` to improve code quality

### PR DESCRIPTION
**Pull request by Jinksi**
Based on #374. Please wait for it to be merged before reviewing/merging.

## Description

This PR only fixes PHPCS violations in the `WC_Subscriptions_Tracker` class to improve code quality. No changes to the underlying logic are expected.

## How to test this PR

1. Enable WC Tracking in **WC Settings → Advanced → WooCommerce.com → Enable Tracking**.
1. Run `WC_Tracker::get_tracking_data()['extensions']['wc_subscriptions']['settings']` with the [WP Console](https://wordpress.org/plugins/wp-console/) plugin. The output should be identical on `trunk` and this branch. Toggle settings such as `enable_early_renewal_via_modal` to check the enabled/disabled output.
2. Run `./vendor/bin/phpcs includes/class-wc-subscriptions-tracker.php` in your terminal. On `trunk` you should see errors/warnings. On this branch, you should not see any violations.
   Note: running phpcs directly from `./vendor/bin/` skips the "only changed LOC" rule that we use for PHPCS GH checks.

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Review by shendy-a8c — COMMENTED** [review]
Code diff looks good.

Running `./vendor/bin/phpcs includes/class-wc-subscriptions-tracker.php` returns no warning, so it's good.

However, when I ran `WC_Tracker::get_tracking_data()['extensions']['wc_subscriptions']['settings']` in WP Console per your testing instruction, I got an error.

Screenshot 2023-01-20 at 05 01 07

**Comment by Jinksi** [comment]
@shendy-a8c Hmmm 😕 I can't see any obvious reason for this error based on the changes in this branch.

Do you get this error on `trunk`?

**Comment by shendy-a8c** [comment]
I tried `trunk` and this PR's branch, with HPOS disabled and enabled. I got that error on all. Let me try to investigate why.

**Comment by Jinksi** [comment]
This could be due to #374, which has been merged. Do you see this error when using subs-core 5.1.0?

Otherwise, maybe it has something to do with WC version or PHP version. 🤔

**Comment by Jinksi** [comment]
It looks like @shendy-a8c's error was due to the WC Tracking setting being disabled.

I've added the following to the testing instructions:

1. Enable WC Tracking in **WC Settings → Advanced → WooCommerce.com → Enable Tracking**.

**Review by shendy-a8c — APPROVED** [review]
Yup, after enabling wp-admin > WooCommerce > Settings > Advanced > WooCommerce.com > Enable Tracking, executing `WC_Tracker::get_tracking_data()['extensions']['wc_subscriptions']['settings']` in WP Console does not throw an error and the value when I am at this PR's branch compared to trunk.

**Pull request merged**
