### PR TITLE
Ensure trial period form data is set before use.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
Fixes #

## Description

Adds an `empty()` logic check before using the trial period form data. 

**Question:** At the moment if the data is not saved the fields are set to their defaults. Should I add some further logic checking to avoid replacing data if it's already set? 

## How to test this PR

1. Create a simple subscription product.
2. Remove the trial period from the form data by disabling the field (run `$$( '.wc_input_subscription_trial_period' ).forEach( el => el.setAttribute( 'disabled', 'disabled' ) );` in the browser console
3. Save the product
   - on trunk you will experience a fatal error
   - on this branch you will not
4. Reload the edit product page
5. Set a trial length and modify the period
6. Save the product
7. Ensure the trial length and period are set as expected
8. Create a variable subscription product
9. Create some attributes to use as variation
10. Generate the variations
11. Remove the trial period from the form data by disabling the field (run the same code in the browser console)
12. Save the product (there is currently no fatal on the trunk) 
13. Reload the edit product page
14. Set a trial length and modify the period for variations
15. Save the product

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
@dkotter: Unable to ping you for a review on this via GH, are you able to take a look at the code?

**Review by dkotter — APPROVED** [review]
Code looks good to me.

In regards to this:

> Question: At the moment if the data is not saved the fields are set to their defaults. Should I add some further logic checking to avoid replacing data if it's already set?

My initial thoughts are yes, probably good to fallback to existing data if it's set, otherwise using the defaults. That said, I'm not sure what scenarios would lead to this data not being set. Is there a likely scenario where someone saved proper data then came back later and re-saved but not all fields were set, thus leading to a scenario where we would have existing data to use?

If that isn't a likely scenario, may not be worth the extra effort to support that.

**Comment by peterwilsoncc** [comment]
@dkotter I've done some further digging. 

This relates to Pre-Orders#393 and managing incompatible product features. 

If a trial period is removed and a pre-order enabled, with the current WIP code the trial data won't be submitted so it's probably best to use the defaults as that will ensure the database doesn't contain the incorrect data.

**Review by james-allan — APPROVED** [review]
Changes look good. Thanks for the PR @peterwilsoncc

**Comment by peterwilsoncc** [comment]
@james-allan Thanks for the review, once y'all merge this are you able to let me know which version of Subs it will be included in so I can update the minimum requirements in Pre-Orders#497

**Comment by james-allan** [comment]
> Thanks for the review, once y'all merge this are you able to let me know which version of Subs it will be included in so I can update the minimum requirements in Pre-Orders#497

No problem @peterwilsoncc. This will be included in subscriptions-core 7.5 which will be **WC Subscriptions 6.7.0**

**Comment by james-allan** [comment]
Just noting that this PR was missing a changelog. I've added one in https://github.com/Automattic/woocommerce-subscriptions-core/commit/36e21730f5f322c4fed3f17707334be72dfd552d.

**Pull request merged**
