### PR TITLE
Update the notifications-related admin notice's copy

### PR DESCRIPTION
**Pull request by xristos3490**
## Description

This PR improves the wording of the admin notice for the notifications feature.

## Screenshot
Screenshot 2024-11-01 at 5 12 45 PM

## How to test this PR

N/A
This changes the copy of existing functionality.

If the notice was previously dismissed, remove the option via`delete_option('wcs_hide_customer_notifications_notice')` and disable the notifications to display the notice on a store with existing notifications.

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Review by peterfabian — APPROVED** [review]
✅ Link to docs works
✅ Link to settings works 
✅ Copy is beautiful as can be

:shipit:

**Review by mattallan — APPROVED** [review]
Admin notice and updated copy LGTM 💯 Thanks!

I was wondering if we should add a cutoff version so that we stop showing this "new feature" notice i.e. only show the notice for the next 3 minor versions?

I think a notice showing up on every new WooCommerce Subscriptions store indefinitely could be annoying, so I'm thinking either a cut-off time/version or we create an issue to remove this notice after some time has elapsed. Thoughts?

**Comment by mattallan** [comment]
While I was just testing the PR again, I noitced I couldn't close the notice. Turns out there was a bug in `WCS_Admin_Notice`. Fixed in [29f1fef](https://github.com/Automattic/woocommerce-subscriptions-core/pull/713/commits/29f1fefc9a4580765e5bf7415c43ac9791d869ed)

**Comment by xristos3490** [comment]
Thanks for the review, @mattallan, and nice catch on the WCS_Admin_Notice controller! 🙇‍♂️ 

> I think a notice showing up on every new WooCommerce Subscriptions store indefinitely could be annoying, so I'm thinking either a cut-off time/version or we create an issue to remove this notice after some time has elapsed. Thoughts?

Totally, agree! I created a followup here:
- https://github.com/Automattic/woocommerce-subscriptions-core/issues/715

**Pull request merged**
