### PR TITLE
Fix: set up integration for Mini Cart Block and add new filter to compatible blocks.

### LINKED ISSUE #5642: Mini Cart: Subscription period and amount due is missing
## Describe the bug
The Mini Cart is missing the subscription period and amount due description at the time of purchase. These information should be added because missing it make customers confused.	

## To reproduce

1. Activate WooCommerce Subscriptions.
2. Add Mini Cart to the header.
3. Create a subscription product with the free trial.
4. On the front end, add that product to the cart.
5. See the cart block has the amount due and subscription period.
6. See Mini Cart content is missing that information.

## Expected behavior
Mini Cart contents should show the due amount and subscriptions period.

### WordPress (please complete the following information):
* Core version: 5.9
* Gutenberg version (if installed): 12.4.1
* WooCommerce version: 6.3.0-dev
* WooCommerce Blocks version: 6.9.0-dev
* Site language:
* Any other plugins installed: WooCommerce Subscriptions 4.0.1

## Additional context
Original issue #5278

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5642

## Description

This PR sets up the Subscriptions integration for the Mini Cart block to display the amount due and subscriptions period inside the Mini Cart Contents. This also adds a new filter (`wcs_compatible_blocks`) and refactors `WC_Subscriptions_Core_Plugin::setup_blocks_integration`.

image

## How to test this PR

1. On WP 5.9, clone and build (`npm run dev`) https://github.com/woocommerce/woocommerce-gutenberg-products-block@trunk.
2. Add Mini Cart block to the header.
3. Create/edit a subscription product with free trial.
4. On the front end, add that subscription product to the cart.
5. Open the Mini Cart, see the amount due and subscription period info in the products table.

## Product impact

WooCommerce Blocks.

- [ ] Added changelog entry (or does not apply)
- [x] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref

### CODE REVIEW

**Comment by brucealdridge** [comment]
@dinhtungdu this looks good on the surface, are you able to fix up the phpcs issues?

**Review by brucealdridge — CHANGES_REQUESTED** [review]
Thanks for this @dinhtungdu can you fix up the phpcs issues.

**Comment by dinhtungdu** [comment]
@brucealdridge I'm sorry for the delay, I was on PTO last week. I fixed the linting issue in 1019bae, please take another look.

**Review by brucealdridge — APPROVED** [review]
LGTM. thanks

**Comment by mattallan** [comment]
Thanks @brucealdridge and @dinhtungdu, I've just added a changelog entry for this one

Once the github checks have passed I'll merge this one in 🙌

**Pull request merged**
