### PR TITLE
Introduce automated CSS linting

### LINKED ISSUE #66: Update CSS to match current WP standards.
## Describe the bug

Currently css isn't meeting all of the standards set in https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/

## To Reproduce

1. Run `wp-scripts lint-css assets/css`
2. see errors 

### Expected behavior

No errors / warnings

### Actual behavior

```
> wp-scripts lint-style assets/css


assets/css/about.css
  10:11  ✖  Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation
  11:15  ✖  Expected quotes around "WooCommerce"            font-family-name-quotes
  12:11  ✖  Expected single quotes                          string-quotes
  73:25  ✖  Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation
  74:25  ✖  Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation
  75:11  ✖  Expected single quotes                          string-quotes
  78:25  ✖  Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation
```

## Product impact

Should have no impact on products, internal changes to meet coding standards only

- [x] Does this issue affect WooCommerce Subscriptions? no
- [x] Does this issue affect WooCommerce Payments? no

## Additional context

see also #32

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #66

## Description

Introduces css checking against WP standards.

## How to test this PR

As most of the changes are code style only, testing shouldn't be required.

## Product impact

- [x] Added changelog entry (or **does not apply**)
- [x] Will this PR affect WooCommerce Subscriptions? no
- [x] Will this PR affect WooCommerce Payments? no

### CODE REVIEW

**Review by mattallan — APPROVED** [review]
Hey @brucealdridge, these changes look good!

Just out of curiosity, did you use an automated script to fix these up, or were they manual edits? Regardless, I sifted through each change and it LGTM :+1:

**Comment by brucealdridge** [comment]
> Just out of curiosity, did you use an automated script to fix these up

108594d was find and replace with regex
fcda1e8 was using the `npm run format:css` command
062520b was 100% manual changes.

I was a little worried about some of the changes. But a quick search resolved that (both support for `::before/after` and quotes & case sensitivity for font names)

**Comment by brucealdridge** [comment]
Holding off merging until #59 has been approved. Then will merge both in at the same time.

**Comment by aprea** [comment]
@brucealdridge apologies for the slow review on this PR. I'm noticing a few changes when I run `npm run format:js`.

Keen to hear your thoughts on whether we should add these changes to this PR to establish a good baseline?

p.s. I think we'll need to add a `.eslintignore` file as I noticed changes were introduced in vendor files (e.g. `assets/js/admin/moment.js`) when I run `npm run format:js`.

**Pull request merged**
