### PR TITLE
v1.3.0 release.

### PR DESCRIPTION
**Pull request by shendy-a8c**
## Description

This PR:
- Updates changelog release date for `1.3.0`.
- Updates version in `package.json` and `woocommerce-subscriptions-core.php` to `1.3.0`.
- Updates `package-lock.json` as a result of running `npm install`.
- Updates `build/index.asset.php` and `build/index.js` as a result of running `npm run build`.

## How to test this PR

- Make sure release date for `1.3.0` is correct.
- Make sure versions are updated in `package.json` and `woocommerce-subscriptions-core.php`.

## Product impact

WooCommerce Payments and WooCommerce Subscriptions.

- [x] Added changelog entry (or does not apply)
- [x] Will this PR affect WooCommerce Subscriptions? not until WooCommerce Subscriptions loads `1.3.0`. 4290-gh-woocommerce/woocommerce-subscriptions
- [x] Will this PR affect WooCommerce Payments? not until WooCommerce Payments loads `1.3.0`. https://github.com/Automattic/woocommerce-payments/pull/3550

### CODE REVIEW

**Comment by aprea** [comment]
>Updates package-lock.json as a result of running npm install.

Hey @shendy-a8c, with this change you have downgraded the `lockfileVersion` from `2` to `1`.

I suspect you're using a relatively old version of `node` because of the version required by `woocommerce-payments` (i.e. `12.22.6`).

You probably want to run `nvm install --lts` and then `nvm use --lts`, this will install node `16.13.1`.

That way, when you run `npm install`, you won't downgrade the `package-lock.json` file.

**Comment by aprea** [comment]
I have created a PR to revert the changes in the `package-lock.json` file https://github.com/Automattic/woocommerce-subscriptions-core/pull/79

**Review by aprea — APPROVED** [review]
Other than the issue mentioned above, this LGTM ✅

**Comment by shendy-a8c** [comment]
Thank you for the detailed review, @aprea!

You're right I use `6.14.8` npm and `14.15.1` node.
I am not sure what's the implication but downgrading seems bad.
It makes me think that we need a more consistent environment to build packages, maybe dockerize it.

I have approved https://github.com/Automattic/woocommerce-subscriptions-core/pull/79 and once that's merged, I can go ahead to merge this PR.

**Pull request merged**
